(function(root){
  'use strict';
  const dictionary=new Map();let language='ru',matcher;
  const add=pairs=>{for(const[ru,en]of pairs)dictionary.set(ru,en);matcher=null;};
  function text(value,target=language){const source=String(value);if(target!=='en')return source;if(!matcher)matcher=new RegExp([...dictionary.keys()].sort((a,b)=>b.length-a.length).map(s=>`${/^[А-Яа-яЁё]/.test(s)?'(?<![А-Яа-яЁё])':''}${s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}${/[А-Яа-яЁё]$/.test(s)?'(?![А-Яа-яЁё])':''}`).join('|'),'g');return source.replace(matcher,s=>dictionary.get(s));}
  function html(source){return language==='en'?source.split(/(<[^>]*>)/g).map(part=>part.startsWith('<')?part.replace(/(aria-label|title|placeholder)="([^"]*)"/g,(_,attr,value)=>`${attr}="${text(value)}"`):text(part)).join(''):source;}
  const originals=new WeakMap(),attributes=new WeakMap();
  function translateDOM(){if(!root.document?.createTreeWalker)return;const walker=document.createTreeWalker(document.body,4);let node;
    while((node=walker.nextNode())){if(['SCRIPT','STYLE','TEXTAREA'].includes(node.parentElement?.tagName))continue;let entry=originals.get(node);if(!entry||node.nodeValue!==entry.last)entry={ru:node.nodeValue};entry.last=text(entry.ru);node.nodeValue=entry.last;originals.set(node,entry);}
    document.querySelectorAll('[aria-label],[title],[placeholder]').forEach(el=>{let saved=attributes.get(el)||{};for(const attr of ['aria-label','title','placeholder'])if(el.hasAttribute(attr)){saved[attr]??=el.getAttribute(attr);el.setAttribute(attr,text(saved[attr]));}attributes.set(el,saved);});
  }
  function setLanguage(value){if(!['ru','en'].includes(value))return false;language=value;try{root.localStorage?.setItem('isekai-idle-language',value);}catch{}if(root.document){document.documentElement.lang=value;document.querySelectorAll('[data-language]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.language===value)));}return true;}
  try{if(root.localStorage?.getItem('isekai-idle-language')==='en')language='en';}catch{}
  const api={get language(){return language;},get locale(){return language==='en'?'en-US':'ru-RU';},add,text,html,setLanguage,translateDOM};root.IsekaiLocale=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
  add([
    ['Монеты','Coins'],['Травы','Herbs'],['Духовная энергия','Qi'],['Осколки','Relic shards'],['Репутация','Reputation'],['Древесина','Wood'],['Руда','Ore'],['Пилюли','Pills'],['Влияние','Influence'],['Припасы','Supplies'],['Звёздная эссенция','Star essence'],['Миры','Worlds'],
    ['Безвестный чужак','Unknown outsider'],['Начинающий практик','Novice cultivator'],['Ученик секты','Sect disciple'],['Глава слабой секты','Leader of a small sect'],['Правитель города','City ruler'],['Владыка планеты','Planet sovereign'],['Звёздная держава','Stellar empire'],['Хранитель галактики','Guardian of the galaxy'],
    ['Выжить и найти свой путь','Survive and find your path'],['Техники, снаряжение и первые испытания','Techniques, equipment and first trials'],['Поручения, репутация и турнир','Assignments, reputation and the tournament'],['Ученики, рабочие и алхимия','Disciples, workers and alchemy'],['Районы, торговые маршруты и снабжение','Districts, trade routes and supplies'],['Мировые узлы, порталы и вторжения','World nodes, portals and invasions'],['Колонии, флот и галактическая экспансия','Colonies, fleets and galactic expansion'],['Законы мироздания и наследие души','Laws of creation and the soul’s legacy'],
    ['Ты очнулся у дороги. Ни денег, ни техники, ни покровителя. В руинах неподалёку что-то зовёт тебя.','You awaken beside a road, with no money, techniques or patron. Something calls to you from the nearby ruins.'],
    ['В осколке обнаружена техника Пустого Неба. Теперь предстоит заслужить место в секте.','The shard reveals the Empty Sky technique. Now you must earn your place in a sect.'],
    ['Ты принят во внешние ученики. Доступ к библиотеке придётся заслужить. Побеждённый соперник уже ищет поддержки своего клана.','You join the disciples. Access to the library must be earned. Your defeated rival is already seeking his clan’s support.'],
    ['После конфликта с кланом тебе досталось разорённое убежище. Трое последователей решили остаться. Теперь их будущее зависит от тебя.','A conflict with the clan leaves you a ruined refuge. Three followers stay with you. Their future is now in your hands.'],
    ['Секта защитила долину. Поселения признали твою власть. Город требует торговли, снабжения и устойчивого управления.','Your sect protects the valley, and its settlements accept your rule. The city needs trade, supplies and steady leadership.'],
    ['Разрозненные земли объединены. В мировом ядре обнаружен след древней сети порталов. За пределами неба есть другие владыки.','The scattered lands unite. The world’s core holds traces of an ancient portal network. Other sovereigns await beyond the sky.'],
    ['Первый межзвёздный переход совершён. Теперь сила героя должна поддерживать целую сеть миров.','Your first interstellar crossing succeeds. Your strength must now sustain a network of worlds.'],
    ['Твои миры связаны в галактический союз. Дальнейший путь лежит через понимание законов пространства и новое рождение.','Your worlds form a galactic union. Your path continues through the laws of space and a new life.'],
    ['Работать над заказом','Work on a contract'],['Исследовать руины','Explore the ruins'],['Медитировать','Meditate'],['Осваивать технику','Practice techniques'],['Поручения секты','Sect assignments'],['Управлять владениями','Manage your domain'],['Постигать законы','Study cosmic laws'],
    ['Сверяет накладные для принятого заказа. На время работы медитация останавливается.','Check invoices for your current contract. Meditation pauses while you work.'],['Травы, осколки и первая находка после 10 минут исследования.','Find herbs and relic shards. Your first discovery takes 10 minutes of exploration.'],['Успокаивает разум. После находки накапливает понимание и духовную энергию.','Calm your mind. After the discovery, accumulate insight and qi.'],['Постепенно усиливает выбранный боевой стиль.','Gradually improve your martial mastery and practice the active technique.'],['Репутация, монеты и травы. Репутация открывает библиотеку.','Earn reputation, coins and herbs. Reputation unlocks the library.'],['Лично укреплять влияние организации.','Personally strengthen your organization’s influence.'],['Ускоренная культивация и сбор звёздной эссенции.','Faster cultivation and gathering of star essence.'],
    ['Обитель учеников','Disciples’ quarters'],['Духовный сад','Spirit garden'],['Торговый район','Market district'],['Склад снабжения','Supply depot'],['Мировой узел','World node'],['Звёздный корабль','Starship'],['Обсерватория законов','Observatory of laws'],['Садовники','Gardeners'],['Лесорубы','Woodcutters'],['Рудокопы','Miners'],['Алхимики','Alchemists'],['Ученики','Disciples'],
    ['Вместимость +3; пригласить последователей можно отдельно.','Capacity +3; recruit followers separately.'],['+0,06 трав/сек.','+0.06 herbs/sec.'],['Открывает дополнительный торговый маршрут.','Unlocks an additional trade route.'],['+0,08 припасов/сек. для караванов и флота.','+0.08 supplies/sec for caravans and fleets.'],['+0,015 эссенции/сек. и +20 силы планетарного щита.','+0.015 essence/sec and +20 planetary shield power.'],['Увеличивает дальность экспансии. Флот расходует припасы во время похода.','Extend your reach. The fleet consumes supplies during expeditions.'],['+20% скорости личного развития за каждую обсерваторию.','+20% personal development speed per observatory.'],
    ['Присесть','Do a squat'],['Пробежать отрезок','Run a lap'],['Подмести двор','Sweep the yard'],['Перенести ящики','Carry crates'],['Осмотреть развалины','Inspect the ruins'],['+0,04 тела','+0.04 body'],['+0,07 тела','+0.07 body'],['+1 шаг заказа на уборку','+1 step of the sweeping contract'],['+1 шаг заказа на разгрузку','+1 step of the unloading contract'],['+2 сек исследования и +0,05 трав','+2 sec exploration and +0.05 herbs'],
    ['Уборка двора Мэй','Sweep Mei’s yard'],['Разгрузка телеги','Unload a cart'],['Сверить накладные','Check invoices'],['10 подметаний. Выполняется кликами, пока ты медитируешь.','10 sweeps. Click to work while meditation continues.'],['8 переносов ящика. Нужен показатель тела 1; выполняется кликами.','Carry 8 crates. Requires body 1; completed by clicking.'],['3 минуты фоновой работы. Пока работаешь, медитация не идёт.','3 minutes of idle work. Meditation pauses while you work.'],
    ['Сутра Пустого Неба','Empty Sky Sutra'],['Корни камня','Roots of Stone'],['Слух зелёных жил','Listening to Green Veins'],['Дыхание тихой реки','Quiet River Breathing'],['Меч облачного перевала','Cloud Pass Sword'],['Нефритовый круг','Jade Circle'],['Возвращающийся клинок','Returning Blade'],['Письмена беззвёздного неба','Script of the Starless Sky'],
    ['Наследие из храма','Temple legacy'],['Урок Жэня в деревне','Zhen’s lesson in the village'],['Помощь Линь в лесу','Helping Lin in the forest'],['Спасение Сэня в лесу','Rescuing Sen in the forest'],['Урок Юнь в горах','Yun’s lesson in the mountains'],['Ученичество в Нефритовой Роще','Discipleship in the Jade Grove'],['Учёба в Облачном Пределе','Study at Cloud’s Edge'],['Архив секты Пустого Неба','Empty Sky sect archives'],
    ['Понимание от медитации +8% за ранг.','Meditation insight +8% per rank.'],['Тело от кликов +8% за ранг.','Body gains from clicks +8% per rank.'],['Травы при исследовании +8% за ранг.','Exploration herbs +8% per rank.'],['Энергия от медитации +8% за ранг.','Meditation qi +8% per rank.'],['Боевая сила +8% за ранг.','Combat power +8% per rank.'],['Травы при исследовании +8% и энергия медитации +4% за ранг.','Exploration herbs +8% and meditation qi +4% per rank.'],['Боевая сила +8% и освоение техники +4% за ранг.','Combat power +8% and martial mastery +4% per rank.'],['Понимание +8% и энергия медитации +4% за ранг.','Insight +8% and meditation qi +4% per rank.'],
    ['Смертный','Mortal'],['Пробуждение души','Soul awakening'],['Пробуждение','Awakening'],['Сбор энергии','Qi gathering'],['Основание','Foundation'],['Духовное ядро','Spirit core'],['Небесный путь','Heavenly path'],['Звёздный дух','Stellar spirit'],['Закон пространства','Law of space'],
    ['Дорожный разбойник','Road bandit'],['Страж руин','Ruins guardian'],['Ученик Белого Клыка','White Fang disciple'],['Первый соперник','First rival'],['Внутренний ученик','Inner disciple'],['Наследник клана','Clan heir'],['Старейшина соперников','Rival elder'],['Чемпион долины','Valley champion'],['Лорд приграничья','Border lord'],['Владыка города','City sovereign'],['Хранитель континента','Continent guardian'],['Небесный посланник','Heavenly envoy'],['Владыка океанов','Ocean sovereign'],['Страж мирового ядра','World core guardian'],['Звёздный захватчик','Stellar invader'],['Лорд спутника','Moon lord'],['Пожиратель миров','World devourer'],['Страж портала','Portal guardian'],['Чемпион звёзд','Star champion'],['Владыка системы','System sovereign'],['Адмирал пустоты','Void admiral'],['Галактический претендент','Galactic challenger'],['Хранитель законов','Keeper of laws'],['Древний бессмертный','Ancient immortal'],['Судья пространства','Judge of space'],['Страж вечности','Guardian of eternity'],['Эхо бесконечности','Echo of infinity']
  ]);
})(globalThis);
