(function(root){
  'use strict';
  // Original in-world sayings. Decorative randomness never consumes world.seed.
  const groups=[
    {id:'beginning',min:0,max:1,source:['Заметки чужака','An outsider’s notes'],lines:[
      ['Чужой мир становится ближе после первого доброго слова.','A strange world feels closer after the first kind word.'],
      ['Сначала найди воду. Великий путь подождёт до утра.','Find water first. The great path can wait until morning.'],
      ['Пустые карманы не мешают держать слово.','Empty pockets do not prevent you from keeping your word.'],
      ['Начало пути редко похоже на начало легенды.','The start of a journey seldom resembles the start of a legend.'],
      ['Крыша над головой тоже бывает первой победой.','A roof over your head can be your first victory.'],
      ['Не стыдись работы, которая кормит тебя сегодня.','Do not be ashamed of the work that feeds you today.'],
      ['Незнакомая дорога не требует незнакомого сердца.','An unfamiliar road does not require an unfamiliar heart.'],
      ['Тот, кто поделился ужином, уже изменил твою историю.','Someone who shares dinner has already changed your story.'],
      ['Прежде чем искать сокровище, узнай имя хозяина дома.','Before seeking treasure, learn your host’s name.'],
      ['Слабость — положение дел, а не обещание на всю жизнь.','Weakness is a circumstance, not a lifetime commitment.'],
      ['Первое орудие выживания — внимательность.','The first tool of survival is attention.'],
      ['Не всякая протянутая рука требует платы.','Not every helping hand demands payment.'],
      ['Один честный заказ полезнее десяти обещаний богатства.','One honest job is worth more than ten promises of wealth.'],
      ['В новом мире старые добрые привычки всё ещё полезны.','Good old habits still help in a new world.'],
      ['Умение попросить помощи не делает тебя слабее.','Knowing how to ask for help does not make you weaker.'],
      ['Найденная тропа начинается с замеченного следа.','A discovered path begins with a noticed footprint.'],
      ['Не нужно быть избранным, чтобы сделать полезное дело.','You need not be chosen to do something useful.'],
      ['Маленькая плата сегодня покупает возможность завтра.','A small wage today buys an opportunity tomorrow.'],
      ['Усталость проходит легче рядом с очагом.','Weariness passes more easily beside a hearth.'],
      ['Первые друзья редко знают, кем ты станешь.','Your first friends seldom know who you will become.'],
      ['Сохрани благодарность дольше, чем чужой хлеб.','Keep your gratitude longer than the bread you receive.'],
      ['Потеряться можно и на знакомой дороге, если спешить.','Even a familiar road can lose you when you rush.'],
      ['Чистый двор не открывает небеса, но открывает двери.','A clean yard does not open heaven, but it opens doors.'],
      ['Путь растёт из решений, принятых без свидетелей.','A path grows from decisions made without witnesses.'],
      ['Новая жизнь не обязана начинаться с новой ошибки.','A new life need not begin with a new mistake.'],
      ['Не путай отсутствие силы с отсутствием выбора.','Do not confuse a lack of strength with a lack of choice.'],
      ['Обычный день может стать началом необычной судьбы.','An ordinary day can begin an extraordinary destiny.'],
      ['Запомни дорогу домой, прежде чем идти за тайной.','Remember the way home before following a mystery.'],
      ['Первый шаг принадлежит тебе, даже если путь показал другой.','The first step is yours even if someone else showed the path.'],
      ['Иногда будущее начинается с починенного колеса.','Sometimes the future begins with a repaired wheel.']
    ]},
    {id:'body',min:0,source:['Заметки о тренировке','Training notes'],lines:[
      ['Сильные ноги вырастают из повторений, а не из обещаний.','Strong legs grow from repetition, not promises.'],
      ['Ровная спина важнее громкого крика.','A straight back matters more than a loud shout.'],
      ['Тело помнит то, что разум откладывал на завтра.','The body remembers what the mind postponed until tomorrow.'],
      ['Последнее правильное повторение ценнее лишнего рывка.','The last correct repetition is worth more than an extra lunge.'],
      ['Тренируйся так, чтобы суметь вернуться завтра.','Train so that you can return tomorrow.'],
      ['Выносливость не любит хвастовства.','Stamina has little patience for boasting.'],
      ['Сначала удержи стойку, потом удерживай удар.','Hold your stance before trying to hold a blow.'],
      ['Крепкое тело строится без зрителей.','A sturdy body is built without an audience.'],
      ['Не каждое дрожание рук означает поражение.','Not every trembling hand signals defeat.'],
      ['Правильный шаг начинается раньше движения стопы.','A good step begins before the foot moves.'],
      ['Отдых сохраняет труд, который уже сделан.','Rest preserves the work already done.'],
      ['Упражнение становится легче после того, как стал сильнее ты.','An exercise grows easier after you grow stronger.'],
      ['Не считай себя слабым за то, что устал.','Do not call yourself weak merely because you are tired.'],
      ['Сила без устойчивости быстро теряет равновесие.','Strength without stability soon loses its balance.'],
      ['Каждый присед оставляет след, которого никто не видит.','Every squat leaves a trace nobody can see.'],
      ['Беги своим темпом: чужие ноги не пройдут твой путь.','Run at your pace; another’s legs cannot travel your path.'],
      ['Не спорь с усталостью — научись распределять усилие.','Do not argue with fatigue; learn to distribute your effort.'],
      ['Техника бережёт силу для нужного мгновения.','Technique saves strength for the moment that needs it.'],
      ['Слабое место можно укрепить, если перестать его скрывать.','A weakness can grow stronger once you stop hiding it.'],
      ['Один точный удар начинается с сотни спокойных движений.','One precise strike begins with a hundred calm movements.'],
      ['Тело не узнает о решении тренироваться, пока ты не начнёшь.','Your body will not hear your training plans until you begin.'],
      ['Предел показывает, где работа продолжается завтра.','A limit shows where tomorrow’s work resumes.'],
      ['Сохраняй дыхание даже тогда, когда хочется спешить.','Keep your breathing steady even when you want to rush.'],
      ['Не ищи тяжёлый меч для неподготовленной руки.','Do not seek a heavy sword for an unprepared hand.'],
      ['Медленный прогресс тоже меняет исход следующего боя.','Slow progress still changes the next fight’s outcome.'],
      ['Стойка не должна ломаться раньше твоей решимости.','Your stance should not break before your resolve.'],
      ['Плечи несут меньше, когда ноги стоят правильно.','Your shoulders carry less when your feet stand correctly.'],
      ['Дисциплина полезна в день, когда вдохновения нет.','Discipline helps on the day inspiration does not arrive.'],
      ['Сегодняшняя разминка бережёт завтрашнюю силу.','Today’s warm-up protects tomorrow’s strength.'],
      ['Победа над привычкой приходит раньше победы над соперником.','Victory over a habit comes before victory over a rival.']
    ]},
    {id:'breath',min:0,source:['Записи о дыхании','Notes on breathing'],lines:[
      ['Тишина не пуста, если ты научился слушать.','Silence is not empty once you learn to listen.'],
      ['Поток не становится яснее от нетерпения.','Impatience does not make the current clearer.'],
      ['Понимание начинается там, где заканчивается угадывание.','Understanding begins where guessing ends.'],
      ['Спокойный вдох не обязан быть глубоким.','A calm breath need not be a deep one.'],
      ['Не держи мысль крепче, чем она держит тебя.','Do not hold a thought tighter than it holds you.'],
      ['Медитация учит замечать возвращение внимания.','Meditation teaches you to notice attention returning.'],
      ['Сначала узнай свой ритм, затем меняй его.','Learn your rhythm before changing it.'],
      ['Сидеть спокойно иногда труднее, чем поднять камень.','Sitting calmly can be harder than lifting a stone.'],
      ['Вдох не повторяет прошлый вдох в точности.','No breath repeats the previous one exactly.'],
      ['Ясный разум не торопится отвечать каждому шуму.','A clear mind need not answer every noise.'],
      ['Секрет дыхания редко помещается в громкое название.','The secret of breathing seldom fits a grand name.'],
      ['Не путай покой с отказом от движения.','Do not confuse stillness with abandoning movement.'],
      ['Понимание растёт, пока ты перестаёшь его подгонять.','Understanding grows when you stop hurrying it.'],
      ['Слушай поток, прежде чем пытаться ему приказать.','Listen to the current before trying to command it.'],
      ['Слабая искра тоже видна в спокойной воде.','Even a faint spark is visible in still water.'],
      ['Разум устает от борьбы с собственной усталостью.','The mind tires from fighting its own weariness.'],
      ['Прорыв готовится в минуты, которые кажутся обычными.','A breakthrough is prepared in seemingly ordinary minutes.'],
      ['Не всякая пауза прерывает путь.','Not every pause interrupts the path.'],
      ['Внутренняя ясность не нуждается в чужом одобрении.','Inner clarity needs no outside approval.'],
      ['Оставь место для ответа, прежде чем задавать вопрос.','Leave room for an answer before asking a question.'],
      ['Тишина помогает услышать собственную ошибку.','Silence helps you hear your own mistake.'],
      ['Одну строку можно понять глубже, чем целую книгу.','One line can be understood more deeply than an entire book.'],
      ['Не превращай каждый вдох в испытание.','Do not turn every breath into a trial.'],
      ['Спокойствие возвращается по тому же пути, что внимание.','Calm returns along the same path as attention.'],
      ['Узнать течение полезнее, чем бороться с каждой волной.','Knowing the current helps more than fighting every wave.'],
      ['Понимание оставляет меньше следов, чем громкая победа.','Understanding leaves fewer traces than a loud victory.'],
      ['Удерживай намерение, а не напряжение.','Hold your intention, not your tension.'],
      ['Сначала освободи ладонь, потом прими новое знание.','Open your hand before accepting new knowledge.'],
      ['Путь к ясности не измеряется громкостью слов.','The path to clarity is not measured by loud words.'],
      ['Даже после прорыва дыхание начинается с простого вдоха.','Even after a breakthrough, breathing begins with a simple breath.']
    ]},
    {id:'road',min:0,source:['Дорожные записки','Roadside notes'],lines:[
      ['За каждой вершиной открывается новое небо.','Beyond every summit lies another sky.'],
      ['У каждой тропы есть причина идти медленнее.','Every trail offers a reason to slow down.'],
      ['Карта показывает дорогу, но не объясняет встречу.','A map shows the road, not the encounter.'],
      ['Хороший проводник знает, когда остановиться.','A good guide knows when to stop.'],
      ['Не всякая короткая дорога приводит туда, куда нужно.','Not every short road leads where you need to go.'],
      ['В лесу полезнее смотреть под ноги, чем на свою славу.','In a forest, watch your footing rather than your fame.'],
      ['Дальняя тропа начинается у знакомого порога.','A distant trail begins at a familiar doorstep.'],
      ['Путник узнаёт людей по делам, а не по вывескам.','A traveler knows people by their deeds, not their signs.'],
      ['Иногда обход сохраняет силы для настоящей цели.','Sometimes a detour saves strength for the real goal.'],
      ['Вернуться с пустыми руками лучше, чем не вернуться.','Returning empty-handed is better than not returning.'],
      ['Смотри, что меняется, когда заканчиваются городские стены.','Notice what changes beyond the city walls.'],
      ['Тот, кто бережёт корни, найдёт травы и завтра.','Someone who protects roots will find herbs tomorrow.'],
      ['Не всякий свет под камнем стоит открытой печати.','Not every light beneath a stone is worth breaking a seal.'],
      ['Чужой совет полезен, пока ты помнишь собственную цель.','Another’s advice helps while you remember your own goal.'],
      ['Уходить вовремя — тоже умение путника.','Leaving in time is also a traveler’s skill.'],
      ['Новая дорога меняет вопросы, а не только расстояние.','A new road changes your questions, not just your distance.'],
      ['Переход через горы не отменяет дороги обратно.','Crossing the mountains does not erase the way back.'],
      ['Знакомое имя может оказаться лучшей картой города.','A familiar name can be the best city map.'],
      ['На развилке не обязательно выбирать навсегда.','A choice at a fork need not last forever.'],
      ['Не всякое приглашение обещает лёгкий путь.','Not every invitation promises an easy path.'],
      ['Сохрани знак благодарности, даже если карта промокла.','Keep a token of gratitude even if the map gets wet.'],
      ['Хорошая находка начинается с хорошего наблюдения.','A good discovery begins with a good observation.'],
      ['Дорога учит тому, чего не видно из окна.','The road teaches what a window cannot show.'],
      ['Следы говорят тише, чем зверь, но часто раньше.','Tracks speak more quietly than the beast, but often sooner.'],
      ['Не торгуйся с опасностью, которой ещё не понял.','Do not bargain with a danger you do not yet understand.'],
      ['Попроси название места, прежде чем спрашивать о сокровищах.','Ask the place’s name before asking about its treasures.'],
      ['Скорость пути не равна глубине увиденного.','The speed of a journey is not the depth of what you see.'],
      ['Уставший путник замечает очаг раньше башни.','A weary traveler notices a hearth before a tower.'],
      ['Принеси домой рассказ, который поможет следующему путнику.','Bring home a story that helps the next traveler.'],
      ['За поворотом может ждать помощь, а не только испытание.','Beyond a turn may lie help, not only a trial.']
    ]},
    {id:'disciple',min:2,source:['Правила учеников','Disciples’ precepts'],lines:[
      ['Наставник открывает дверь, но учится ученик.','A mentor opens the door; the disciple does the learning.'],
      ['Носить знак школы легче, чем отвечать за него.','Wearing a school’s badge is easier than answering for it.'],
      ['В библиотеке соперник не мешает читать.','A rival cannot stop you reading in the library.'],
      ['Не сравнивай свой первый урок с чужим последним.','Do not compare your first lesson with another’s last.'],
      ['Спроси о причине движения, а не только о его имени.','Ask why a movement works, not merely its name.'],
      ['Репутация растёт медленнее, чем слух.','Reputation grows more slowly than rumor.'],
      ['Полезное поручение редко выглядит торжественно.','A useful assignment seldom looks ceremonial.'],
      ['Победа на помосте не освобождает от работы завтра.','Victory on the platform does not excuse tomorrow’s work.'],
      ['Чужая техника не обязана подходить твоему пути.','Another’s technique need not suit your path.'],
      ['Благодарность наставнику проявляется в внимании к уроку.','Gratitude to a mentor appears in attention to the lesson.'],
      ['Изученная страница полезнее украденного названия.','A studied page is worth more than a stolen title.'],
      ['Сильный ученик замечает тех, кто отстал.','A strong disciple notices those who fall behind.'],
      ['Не превращай каждое замечание в оскорбление.','Do not turn every correction into an insult.'],
      ['Урок продолжается после закрытия книги.','The lesson continues after the book closes.'],
      ['Смена учения не стирает честно освоенных основ.','Changing a teaching does not erase honestly learned foundations.'],
      ['Поручительство даёт шанс, а не готовую силу.','Sponsorship gives a chance, not ready-made strength.'],
      ['Старая ошибка школы может стать новым вопросом ученика.','A school’s old mistake can become a disciple’s new question.'],
      ['Не всякое знание нужно применять немедленно.','Not every piece of knowledge needs immediate use.'],
      ['Библиотека велика, но читать придётся по одной странице.','The library is vast, but reading still takes one page at a time.'],
      ['Признать незнание — хороший способ начать урок.','Admitting ignorance is a good way to begin a lesson.'],
      ['Не занимай чужое место, пока не понял своё.','Do not take another’s place before understanding your own.'],
      ['Школа крепнет, когда ученики берегут друг друга.','A school grows stronger when disciples protect each other.'],
      ['Слово наставника не заменяет твоей проверки.','A mentor’s word does not replace your own examination.'],
      ['Точность уважает противника больше, чем хвастовство.','Precision respects an opponent more than boasting does.'],
      ['Помни урок, который помог до первой награды.','Remember the lesson that helped before your first reward.'],
      ['Не путай громкое имя школы с собственной подготовкой.','Do not confuse a school’s grand name with your own preparation.'],
      ['Проигранный спор может сохранить хороший вопрос.','A lost argument may preserve a good question.'],
      ['Учение становится твоим через практику.','A teaching becomes yours through practice.'],
      ['Доверие начинается с выполненного маленького поручения.','Trust begins with a small assignment completed.'],
      ['Хороший ученик оставляет после себя ясные записи.','A good disciple leaves clear notes behind.']
    ]},
    {id:'leadership',min:3,source:['Записи главы секты','A sect leader’s records'],lines:[
      ['Люди приходят за надеждой, а остаются за порядком.','People arrive for hope and stay for stability.'],
      ['Пустой склад не заполнить красивой речью.','A fine speech cannot fill an empty storehouse.'],
      ['Сила главы заметна в спокойствии учеников.','A leader’s strength shows in the disciples’ peace.'],
      ['Не обещай защиту там, куда не доходят твои дороги.','Do not promise protection where your roads cannot reach.'],
      ['Договор живёт дольше угрозы.','An agreement lives longer than a threat.'],
      ['Сад требует ухода даже в день великой победы.','A garden needs tending even on the day of a great victory.'],
      ['Хорошее назначение учитывает человека, а не только место.','A good assignment considers the person, not just the position.'],
      ['Ученикам нужны время и еда, а не только наставления.','Disciples need time and food, not just instruction.'],
      ['Ответственность растёт вместе с воротами обители.','Responsibility grows with the refuge’s gates.'],
      ['Не оставляй снабжение на милость удачи.','Do not leave supplies at the mercy of luck.'],
      ['Самый сильный меч не заменяет честного кладовщика.','The strongest sword cannot replace an honest storekeeper.'],
      ['Правитель должен слышать то, что не говорят громко.','A ruler must hear what is not spoken loudly.'],
      ['Торговая дорога соединяет интересы раньше городов.','A trade road connects interests before it connects cities.'],
      ['Уважение не собирается вместе с налогами.','Respect cannot be collected alongside taxes.'],
      ['Позаботься о тихой работе до громкой церемонии.','Attend to quiet work before a loud ceremony.'],
      ['Город узнаёт своего защитника по обычным дням.','A city knows its protector through ordinary days.'],
      ['Чем шире владения, тем важнее ясные правила.','The wider the domain, the more important clear rules become.'],
      ['Не заставляй верность заменять отдых.','Do not make loyalty replace rest.'],
      ['Наставник множит силу, когда учит других решать.','A mentor multiplies strength by teaching others to decide.'],
      ['Порядок должен пережить день твоего отсутствия.','Order must survive a day of your absence.'],
      ['Береги тех, кто замечает неисправность первым.','Protect those who notice a fault first.'],
      ['Надёжный караван начинается с проверенного колеса.','A reliable caravan begins with a checked wheel.'],
      ['Не считай людей расходным материалом победы.','Do not count people as expendable materials for victory.'],
      ['Обитель растёт, когда в ней можно задать вопрос.','A refuge grows when questions can be asked within it.'],
      ['Достаток полезнее, когда не держится на одном человеке.','Prosperity helps more when it does not depend on one person.'],
      ['Оставь место тому, кто сделает работу лучше тебя.','Make room for someone who will do the work better than you.'],
      ['Новая башня не исправляет старый долг.','A new tower does not settle an old debt.'],
      ['Мирный день требует подготовки не меньше битвы.','A peaceful day takes no less preparation than a battle.'],
      ['Чужую просьбу легче услышать без своей спешки.','Another’s request is easier to hear without your own haste.'],
      ['Общее будущее начинается с справедливой доли сегодня.','A shared future begins with a fair share today.']
    ]},
    {id:'cosmos',min:5,source:['Хроники звёздных переходов','Chronicles of stellar crossings'],lines:[
      ['Далёкий мир сначала становится вопросом, потом дорогой.','A distant world becomes a question before becoming a road.'],
      ['Портал соединяет берега, но не создаёт доверие.','A portal joins shores but does not create trust.'],
      ['Между звёздами особенно важно знать путь обратно.','Among the stars, knowing the way back matters most.'],
      ['Один источник не должен поить все миры.','One source should not supply every world.'],
      ['Небо велико, но каждый переход имеет цену.','The sky is vast, but every crossing has a price.'],
      ['Не называй пустым мир, чью историю не прочёл.','Do not call a world empty before reading its history.'],
      ['Новая колония нуждается в хлебе раньше славы.','A new colony needs bread before glory.'],
      ['Законы мира становятся заметнее на его границе.','A world’s laws become clearer at its boundary.'],
      ['Флот силён настолько, насколько надёжно его снабжение.','A fleet is only as strong as its supplies are reliable.'],
      ['Расстояние между мирами не отменяет обещаний.','Distance between worlds does not cancel promises.'],
      ['Свет далёкой звезды может быть старше твоего пути.','A distant star’s light may be older than your journey.'],
      ['Каждый новый узел меняет соседние потоки.','Every new node changes neighboring currents.'],
      ['Межмировой союз начинается с понятного договора.','An interworld alliance begins with a clear agreement.'],
      ['Не спеши менять небо, пока не изучил его равновесие.','Do not rush to change a sky before studying its balance.'],
      ['Чужая планета не обязана жить по привычкам твоей.','Another planet need not live by your planet’s habits.'],
      ['Переход открывает путь, а подготовка сохраняет его.','A crossing opens a route; preparation preserves it.'],
      ['Даже огромный мир начинается для путника с места прибытия.','Even a vast world begins for a traveler at the arrival point.'],
      ['Не измеряй ценность мира только запасами руды.','Do not measure a world’s worth only by its ore.'],
      ['Звёздная карта не заменяет внимательного капитана.','A star chart cannot replace an attentive captain.'],
      ['Пустота не опасна меньше от красивого названия.','A beautiful name does not make the void less dangerous.'],
      ['Укрепи старый переход, прежде чем открывать новый.','Strengthen the old crossing before opening a new one.'],
      ['Мир получает имя не тогда, когда его заметил ты.','A world does not receive its name when you notice it.'],
      ['Космический закон проверяется даже в малом опыте.','A cosmic law is tested even in a small experiment.'],
      ['Не позволяй дальним победам скрывать близкую нехватку.','Do not let distant victories hide nearby shortages.'],
      ['За пределами неба работа не становится менее земной.','Beyond the sky, work is no less grounded.'],
      ['Сначала сделай переход безопасным для следующего корабля.','Make the crossing safe for the next ship first.'],
      ['Большая сеть требует маленьких точных проверок.','A vast network needs small, precise checks.'],
      ['Согласие миров дороже одного громкого приказа.','Agreement between worlds is worth more than one loud command.'],
      ['Не каждую границу нужно пересекать сегодня.','Not every boundary must be crossed today.'],
      ['Звёзды дают направление, но решение остаётся твоим.','Stars give direction; the decision remains yours.']
    ]},
    {id:'legacy',min:7,source:['Летописи души','Annals of the soul'],lines:[
      ['Наследие — то, что помогает без твоего присутствия.','A legacy is what helps without your presence.'],
      ['Новая жизнь не стирает смысл прежней.','A new life does not erase the meaning of the old one.'],
      ['Опыт легче нести, когда он перестал быть гордостью.','Experience is easier to carry once it stops being pride.'],
      ['Не оставляй потомкам только названия своих побед.','Leave your successors more than the names of your victories.'],
      ['Вернуться к началу можно с другим пониманием.','You can return to the beginning with a different understanding.'],
      ['Память полезна, пока не запрещает учиться заново.','Memory helps while it does not forbid learning anew.'],
      ['Самый долгий путь всё ещё состоит из отдельных дней.','The longest journey still consists of individual days.'],
      ['Не путай вечность с бесконечным повторением ошибки.','Do not confuse eternity with endlessly repeating a mistake.'],
      ['Тот, кто продолжит дело, не обязан повторить тебя.','Whoever continues your work need not repeat you.'],
      ['Сила души проявляется в том, что она сохраняет.','A soul’s strength shows in what it preserves.'],
      ['Даже галактике нужны люди, умеющие беречь начало.','Even a galaxy needs people who can protect a beginning.'],
      ['Знание переживает мастера, если его можно понять.','Knowledge outlives its master if it can be understood.'],
      ['Оставь ясную тропу, а не только высокую вершину.','Leave a clear trail, not merely a high summit.'],
      ['Не всякий след становится памятником, но каждый меняет дорогу.','Not every trace becomes a monument, but each changes the road.'],
      ['Прошлая жизнь — учитель, а не приказ.','A past life is a teacher, not a command.'],
      ['Перерождение меняет начало, но не отменяет ответственности.','Rebirth changes the beginning, not the responsibility.'],
      ['Великая история нуждается в честно записанных малых днях.','A great history needs honestly recorded small days.'],
      ['Благодарность способна пройти дальше, чем имя.','Gratitude can travel farther than a name.'],
      ['Урок завершён, когда ученик может идти самостоятельно.','A lesson is complete when the disciple can walk alone.'],
      ['То, что ты создал, должно уметь жить без твоей силы.','What you build must learn to live without your strength.'],
      ['Начать заново легче, если перестать бояться простых задач.','Starting again is easier once you stop fearing simple tasks.'],
      ['Предел жизни не обязан быть пределом её пользы.','A life’s end need not be the end of its usefulness.'],
      ['Сохрани не только ответ, но и причину вопроса.','Preserve not only the answer but the reason for the question.'],
      ['Новая вершина не делает первый шаг ненужным.','A new summit does not make the first step unnecessary.'],
      ['Не требуй от новой жизни немедленно стать прежней.','Do not demand that a new life immediately become the old one.'],
      ['Наследие крепнет, когда его разрешают улучшать.','A legacy grows stronger when others may improve it.'],
      ['Иногда самое ценное учение умещается в заботе.','Sometimes the most valuable teaching fits within an act of care.'],
      ['В памяти души должно остаться место для нового неба.','A soul’s memory should leave room for a new sky.'],
      ['Не бойся быть начинающим после долгого пути.','Do not fear being a beginner after a long journey.'],
      ['Последняя страница может стать чьей-то первой.','The last page may become someone else’s first.']
    ]}
  ];
  const catalog=groups.flatMap(g=>g.lines.map(([ru,en],i)=>({id:`${g.id}:${i}`,group:g.id,min:g.min,max:g.max??7,ru,en,source:g.source})));
  function createRotator(random=Math.random){let active=null,bag=[],poolKey='',context='',nextAt=0;const recent=[];
    return {get(s,now=Date.now(),language='ru'){
      const pool=catalog.filter(q=>s.stage>=q.min&&s.stage<=q.max),key=pool.map(q=>q.id).join('|');
      const currentContext=`${s.stage}:${s.storyStep}:${s.world.location}:${s.world.journey?.destination||''}`;
      if(key!==poolKey){bag=[];poolKey=key;}
      if(!active||currentContext!==context||now>=nextAt){
        if(!bag.length){bag=pool.filter(q=>!recent.includes(q.id));for(let i=bag.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[bag[i],bag[j]]=[bag[j],bag[i]];}}
        active=bag.pop();recent.push(active.id);if(recent.length>20)recent.shift();context=currentContext;nextAt=now+30000;
      }
      return {id:active.id,text:language==='en'?active.en:active.ru,source:active.source[language==='en'?1:0]};
    }};
  }
  const api={catalog,createRotator};root.IsekaiQuotes=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(globalThis);
